# -*- coding: utf-8 -*-
"""ciclo_devops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_prfAo8tFE8H5Zgy5gu94Ag-c5_TDZ0S
"""

print("Trabalho final da disciplina de DevOps")